---
- name: add repokey to APT
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com
  tags: install

- name: add MongoDB repository to APT
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: APT install Mongo
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: turn mongo on
  systemd:
    name: mongod
    enabled: true
    state: started
  tags: install
